// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chiral/v1/agent.proto

package chiralv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type XrayState int32

const (
	XrayState_XRAY_STATE_UNSPECIFIED XrayState = 0
	XrayState_XRAY_STATE_RUNNING     XrayState = 1
	XrayState_XRAY_STATE_STOPPED     XrayState = 2
	XrayState_XRAY_STATE_ERROR       XrayState = 3
)

// Enum value maps for XrayState.
var (
	XrayState_name = map[int32]string{
		0: "XRAY_STATE_UNSPECIFIED",
		1: "XRAY_STATE_RUNNING",
		2: "XRAY_STATE_STOPPED",
		3: "XRAY_STATE_ERROR",
	}
	XrayState_value = map[string]int32{
		"XRAY_STATE_UNSPECIFIED": 0,
		"XRAY_STATE_RUNNING":     1,
		"XRAY_STATE_STOPPED":     2,
		"XRAY_STATE_ERROR":       3,
	}
)

func (x XrayState) Enum() *XrayState {
	p := new(XrayState)
	*p = x
	return p
}

func (x XrayState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (XrayState) Descriptor() protoreflect.EnumDescriptor {
	return file_chiral_v1_agent_proto_enumTypes[0].Descriptor()
}

func (XrayState) Type() protoreflect.EnumType {
	return &file_chiral_v1_agent_proto_enumTypes[0]
}

func (x XrayState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use XrayState.Descriptor instead.
func (XrayState) EnumDescriptor() ([]byte, []int) {
	return file_chiral_v1_agent_proto_rawDescGZIP(), []int{0}
}

type StatScope int32

const (
	StatScope_STAT_SCOPE_UNSPECIFIED StatScope = 0
	StatScope_STAT_SCOPE_INBOUND     StatScope = 1
	StatScope_STAT_SCOPE_OUTBOUND    StatScope = 2
	StatScope_STAT_SCOPE_USER        StatScope = 3
)

// Enum value maps for StatScope.
var (
	StatScope_name = map[int32]string{
		0: "STAT_SCOPE_UNSPECIFIED",
		1: "STAT_SCOPE_INBOUND",
		2: "STAT_SCOPE_OUTBOUND",
		3: "STAT_SCOPE_USER",
	}
	StatScope_value = map[string]int32{
		"STAT_SCOPE_UNSPECIFIED": 0,
		"STAT_SCOPE_INBOUND":     1,
		"STAT_SCOPE_OUTBOUND":    2,
		"STAT_SCOPE_USER":        3,
	}
)

func (x StatScope) Enum() *StatScope {
	p := new(StatScope)
	*p = x
	return p
}

func (x StatScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatScope) Descriptor() protoreflect.EnumDescriptor {
	return file_chiral_v1_agent_proto_enumTypes[1].Descriptor()
}

func (StatScope) Type() protoreflect.EnumType {
	return &file_chiral_v1_agent_proto_enumTypes[1]
}

func (x StatScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatScope.Descriptor instead.
func (StatScope) EnumDescriptor() ([]byte, []int) {
	return file_chiral_v1_agent_proto_rawDescGZIP(), []int{1}
}

type EventKind int32

const (
	EventKind_EVENT_KIND_UNSPECIFIED    EventKind = 0
	EventKind_EVENT_KIND_XRAY_CRASHED   EventKind = 1
	EventKind_EVENT_KIND_XRAY_RESTARTED EventKind = 2
	EventKind_EVENT_KIND_ERROR          EventKind = 3
)

// Enum value maps for EventKind.
var (
	EventKind_name = map[int32]string{
		0: "EVENT_KIND_UNSPECIFIED",
		1: "EVENT_KIND_XRAY_CRASHED",
		2: "EVENT_KIND_XRAY_RESTARTED",
		3: "EVENT_KIND_ERROR",
	}
	EventKind_value = map[string]int32{
		"EVENT_KIND_UNSPECIFIED":    0,
		"EVENT_KIND_XRAY_CRASHED":   1,
		"EVENT_KIND_XRAY_RESTARTED": 2,
		"EVENT_KIND_ERROR":          3,
	}
)

func (x EventKind) Enum() *EventKind {
	p := new(EventKind)
	*p = x
	return p
}

func (x EventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_chiral_v1_agent_proto_enumTypes[2].Descriptor()
}

func (EventKind) Type() protoreflect.EnumType {
	return &file_chiral_v1_agent_proto_enumTypes[2]
}

func (x EventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventKind.Descriptor instead.
func (EventKind) EnumDescriptor() ([]byte, []int) {
	return file_chiral_v1_agent_proto_rawDescGZIP(), []int{2}
}

type UserOpKind int32

const (
	UserOpKind_USER_OP_KIND_UNSPECIFIED UserOpKind = 0
	UserOpKind_USER_OP_KIND_ADD         UserOpKind = 1
	UserOpKind_USER_OP_KIND_REMOVE      UserOpKind = 2
)

// Enum value maps for UserOpKind.
var (
	UserOpKind_name = map[int32]string{
		0: "USER_OP_KIND_UNSPECIFIED",
		1: "USER_OP_KIND_ADD",
		2: "USER_OP_KIND_REMOVE",
	}
	UserOpKind_value = map[string]int32{
		"USER_OP_KIND_UNSPECIFIED": 0,
		"USER_OP_KIND_ADD":         1,
		"USER_OP_KIND_REMOVE":      2,
	}
)

func (x UserOpKind) Enum() *UserOpKind {
	p := new(UserOpKind)
	*p = x
	return p
}

func (x UserOpKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserOpKind) Descriptor() protoreflect.EnumDescriptor {
	return file_chiral_v1_agent_proto_enumTypes[3].Descriptor()
}

func (UserOpKind) Type() protoreflect.EnumType {
	return &file_chiral_v1_agent_proto_enumTypes[3]
}

func (x UserOpKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserOpKind.Descriptor instead.
func (UserOpKind) EnumDescriptor() ([]byte, []int) {
	return file_chiral_v1_agent_proto_rawDescGZIP(), []int{3}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JoinToken     string                 `protobuf:"bytes,1,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_chiral_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chiral_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_chiral_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type RegisterResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Long-term per-node credential. Core stores only a hash; the credential
	// can be revoked individually without affecting other nodes.
	Credential    string `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_chiral_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chiral_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_chiral_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterResponse) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

type AgentFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*AgentFrame_Hello
	//	*AgentFrame_Heartbeat
	//	*AgentFrame_Stats
	//	*AgentFrame_ConfigAck
	//	*AgentFrame_Event
	//	*AgentFrame_Online
	Frame         isAgentFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentFrame) Reset() {
	*x = AgentFrame{}
	mi := &file_chiral_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentFrame) ProtoMessage() {}

func (x *AgentFrame) ProtoReflect() protoreflect.Message {
	mi := &file_chiral_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentFrame.ProtoReflect.Descriptor instead.
func (*AgentFrame) Descriptor() ([]byte, []int) {
	return file_chiral_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentFrame) GetFrame() isAgentFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *AgentFrame) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Frame.(*AgentFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentFrame) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Frame.(*AgentFrame_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentFrame) GetStats() *StatsReport {
	if x != nil {
		if x, ok := x.Frame.(*AgentFrame_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

func (x *AgentFrame) GetConfigAck() *ConfigAck {
	if x != nil {
		if x, ok := x.Frame.(*AgentFrame_ConfigAck); ok {
			return x.ConfigAck
		}
	}
	return nil
}

func (x *AgentFrame) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Frame.(*AgentFrame_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *AgentFrame) GetOnline() *OnlineReport {
	if x != nil {
		if x, ok := x.Frame.(*AgentFrame_Online); ok {
			return x.Online
		}
	}
	return nil
}

type isAgentFrame_Frame interface {
	isAgentFrame_Frame()
}

type AgentFrame_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentFrame_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentFrame_Stats struct {
	Stats *StatsReport `protobuf:"bytes,3,opt,name=stats,proto3,oneof"`
}

type AgentFrame_ConfigAck struct {
	ConfigAck *ConfigAck `protobuf:"bytes,4,opt,name=config_ack,json=configAck,proto3,oneof"`
}

type AgentFrame_Event struct {
	Event *Event `protobuf:"bytes,5,opt,name=event,proto3,oneof"`
}

type AgentFrame_Online struct {
	Online *OnlineReport `protobuf:"bytes,6,opt,name=online,proto3,oneof"`
}

func (*AgentFrame_Hello) isAgentFrame_Frame() {}

func (*AgentFrame_Heartbeat) isAgentFrame_Frame() {}

func (*AgentFrame_Stats) isAgentFrame_Frame() {}

func (*AgentFrame_ConfigAck) isAgentFrame_Frame() {}

func (*AgentFrame_Event) isAgentFrame_Frame() {}

func (*AgentFrame_Online) isAgentFrame_Frame() {}

// Hello is the first frame after the stream is established.
type Hello struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	NodeId       string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AgentVersion string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// Version of the managed Xray-core binary; empty if not installed yet.
	XrayVersion   string `protobuf:"bytes,3,opt,name=xray_version,json=xrayVersion,proto3" json:"xray_version,omitempty"`
	PublicIp      string `protobuf:"bytes,4,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_chiral_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_chiral_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_chiral_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Hello) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetXrayVersion() string {
	if x != nil {
		return x.XrayVersion
	}
	return ""
}

func (x *Hello) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

// Heartbeat carries lightweight system metrics and liveness.
type Heartbeat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent     float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemUsedBytes   uint64                 `protobuf:"varint,2,opt,name=mem_used_bytes,json=memUsedBytes,proto3" json:"mem_used_bytes,omitempty"`
	MemTotalBytes  uint64                 `protobuf:"varint,3,opt,name=mem_total_bytes,json=memTotalBytes,proto3" json:"mem_total_bytes,omitempty"`
	DiskUsedBytes  uint64                 `protobuf:"varint,4,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskTotalBytes uint64                 `protobuf:"varint,5,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	// Instantaneous network throughput, bytes per second.
	NetTxBps  uint64    `protobuf:"varint,6,opt,name=net_tx_bps,json=netTxBps,proto3" json:"net_tx_bps,omitempty"`
	NetRxBps  uint64    `protobuf:"varint,7,opt,name=net_rx_bps,json=netRxBps,proto3" json:"net_rx_bps,omitempty"`
	XrayState XrayState `protobuf:"varint,8,opt,name=xray_state,json=xrayState,proto3,enum=chiral.v1.XrayState" json:"xray_state,omitempty"`
	// Version of the currently applied config; 0 if none applied yet.
	ConfigVersion int64 `protobuf:"varint,9,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	// Version of the Xray-core binary the RUNNING process was started from,
	// canonical form (no leading "v"). Empty when nothing is running.
	//
	// Hello carries a version too, but Hello only happens at stream setup. An
	// in-place binary upgrade does not drop the stream, so without it here Core
	// could never observe that an upgrade landed — it would be judging the
	// outcome of a change it cannot see.
	XrayVersion string `protobuf:"bytes,10,opt,name=xray_version,json=xrayVersion,proto3" json:"xray_version,omitempty"`
	// Version of the binary the NEXT start would use.
	//
	// Two fields rather than one because the two answer different questions and
	// the upgrade path needs both: "did the new kernel actually take over?" is
	// about the running process, while "which kernel do I validate this config
	// against?" is about the one on disk. They agree in the steady state and
	// disagree exactly when something has gone wrong — a swap that did not
	// restart, a rollback, a crash-looping kernel — which is precisely when
	// collapsing them into one number would report the reassuring half.
	InstalledXrayVersion string `protobuf:"bytes,11,opt,name=installed_xray_version,json=installedXrayVersion,proto3" json:"installed_xray_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_chiral_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_chiral_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_chiral_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Heartbeat) GetMemUsedBytes() uint64 {
	if x != nil {
		return x.MemUsedBytes
	}
	return 0
}

func (x *Heartbeat) GetMemTotalBytes() uint64 {
	if x != nil {
		return x.MemTotalBytes
	}
	return 0
}

func (x *Heartbeat) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *Heartbeat) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *Heartbeat) GetNetTxBps() uint64 {
	if x != nil {
		return x.NetTxBps
	}
	return 0
}

func (x *Heartbeat) GetNetRxBps() uint64 {
	if x != nil {
		return x.NetRxBps
	}
	return 0
}

func (x *Heartbeat) GetXrayState() XrayState {
	if x != nil {
		return x.XrayState
	}
	return XrayState_XRAY_STATE_UNSPECIFIED
}

func (x *Heartbeat) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *Heartbeat) GetXrayVersion() string {
	if x != nil {
		return x.XrayVersion
	}
	return ""
}

func (x *Heartbeat) GetInstalledXrayVersion() string {
	if x != nil {
		return x.InstalledXrayVersion
	}
	return ""
}

// StatsReport carries traffic deltas since the previous report, never
// absolute counter values, so an Xray-core restart cannot skew totals.
// Implemented in M3; shape is a draft until then.
type StatsReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*StatEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsReport) Reset() {
	*x = StatsReport{}
	mi := &file_chiral_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsReport) ProtoMessage() {}

func (x *StatsReport) ProtoReflect() protoreflect.Message {
	mi := &file_chiral_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsReport.ProtoReflect.Descriptor instead.
func (*StatsReport) Descriptor() ([]byte, []int) {
	return file_chiral_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *StatsReport) GetEntries() []*StatEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type StatEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Scope StatScope              `protobuf:"varint,1,opt,name=scope,proto3,enum=chiral.v1.StatScope" json:"scope,omitempty"`
	// Inbound/outbound tag, or the per-credential email for STAT_SCOPE_USER.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UplinkBytes   uint64 `protobuf:"varint,3,opt,name=uplink_bytes,json=uplinkBytes,proto3" json:"uplink_bytes,omitempty"`
	DownlinkBytes uint64 `protobuf:"varint,4,opt,name=downlink_bytes,json=downlinkBytes,proto3" json:"downlink_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatEntry) Reset() {
	*x = StatEntry{}
	mi := &file_chiral_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatEntry) ProtoMessage() {}

func (x *StatEntry) ProtoReflect() protoreflect.Message {
	mi := &file_chiral_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatEntry.ProtoReflect.Descriptor instead.
func (*StatEntry) Descriptor() ([]byte, []int) {
	return file_chiral_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *StatEntry) GetScope() StatScope {
	if x != nil {
		return x.Scope
	}
	return StatScope_STAT_SCOPE_UNSPECIFIED
}

func (x *StatEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatEntry) GetUplinkBytes() uint64 {
	if x != nil {
		return x.UplinkBytes
	}
	return 0
}

func (x *StatEntry) GetDownlinkBytes() uint64 {
	if x != nil {
		return x.DownlinkBytes
	}
	return 0
}

// ConfigAck reports the outcome of a ConfigPush.
type ConfigAck struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Applied bool                   `protobuf:"varint,2,opt,name=applied,proto3" json:"applied,omitempty"`
	// Failure detail (e.g. local `xray -test` output) when applied is false.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigAck) Reset() {
	*x = ConfigAck{}
	mi := &file_chiral_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigAck) ProtoMessage() {}

func (x *ConfigAck) ProtoReflect() protoreflect.Message {
	mi := &file_chiral_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigAck.ProtoReflect.Descriptor instead.
func (*ConfigAck) Descriptor() ([]byte, []int) {
	return file_chiral_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigAck) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigAck) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *ConfigAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// OnlineReport lists the source addresses currently connected, per credential.
//
// This is an ABSOLUTE SNAPSHOT, and the deliberate exception to the delta rule
// StatsReport follows. The two have opposite failure modes: traffic counters
// reset to zero when Xray restarts, so absolute values would skew totals —
// whereas an observation set that empties on restart means "we are not
// observing", never "zero devices, lift the limit". Sending the whole set each
// time is what lets Core tell those apart.
//
// Measured against Xray 26.3.27, and the reason for `complete`: a user's online
// count is the number of DISTINCT SOURCE ADDRESSES, not sessions — three
// concurrent connections from one address report as one. Loopback sources are
// excluded from Xray's accounting entirely.
type OnlineReport struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	AtUnix int64                  `protobuf:"varint,1,opt,name=at_unix,json=atUnix,proto3" json:"at_unix,omitempty"`
	// False when the agent could not enumerate everything this round (a timeout
	// partway through the fan-out).
	//
	// Core keeps what such a round did contain and marks the resulting count
	// partial, rather than discarding it: the addresses it DID see are real, and
	// dropping the round would make a persistently slow node look quiet instead
	// of unreliable. What the flag forbids is reading a truncated set as "these
	// are all the addresses in use" — so the count travels with `partial` and is
	// documented as a floor, never a total.
	Complete bool `protobuf:"varint,2,opt,name=complete,proto3" json:"complete,omitempty"`
	// Sent every round even when empty, so silence stays unambiguous. An empty
	// list from Xray has three different causes — the policy is off, nobody is
	// connected, or every source was loopback — and `xray api
	// statsgetallonlineusers` answers all three with `{}` and exit 0.
	Users         []*OnlineUser `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineReport) Reset() {
	*x = OnlineReport{}
	mi := &file_chiral_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineReport) ProtoMessage() {}

func (x *OnlineReport) ProtoReflect() protoreflect.Message {
	mi := &file_chiral_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineReport.ProtoReflect.Descriptor instead.
func (*OnlineReport) Descriptor() ([]byte, []int) {
	return file_chiral_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *OnlineReport) GetAtUnix() int64 {
	if x != nil {
		return x.AtUnix
	}
	return 0
}

func (x *OnlineReport) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *OnlineReport) GetUsers() []*OnlineUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type OnlineUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The per-credential stats key, i.e. user.StatsEmail.
	Email         string      `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Ips           []*OnlineIP `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineUser) Reset() {
	*x = OnlineUser{}
	mi := &file_chiral_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineUser) ProtoMessage() {}

func (x *OnlineUser) ProtoReflect() protoreflect.Message {
	mi := &file_chiral_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineUser.ProtoReflect.Descriptor instead.
func (*OnlineUser) Descriptor() ([]byte, []int) {
	return file_chiral_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *OnlineUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OnlineUser) GetIps() []*OnlineIP {
	if x != nil {
		return x.Ips
	}
	return nil
}

type OnlineIP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	LastSeenUnix  int64                  `protobuf:"varint,2,opt,name=last_seen_unix,json=lastSeenUnix,proto3" json:"last_seen_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineIP) Reset() {
	*x = OnlineIP{}
	mi := &file_chiral_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineIP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineIP) ProtoMessage() {}

func (x *OnlineIP) ProtoReflect() protoreflect.Message {
	mi := &file_chiral_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineIP.ProtoReflect.Descriptor instead.
func (*OnlineIP) Descriptor() ([]byte, []int) {
	return file_chiral_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *OnlineIP) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *OnlineIP) GetLastSeenUnix() int64 {
	if x != nil {
		return x.LastSeenUnix
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EventKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=chiral.v1.EventKind" json:"kind,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AtUnix        int64                  `protobuf:"varint,3,opt,name=at_unix,json=atUnix,proto3" json:"at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_chiral_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_chiral_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_chiral_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *Event) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetAtUnix() int64 {
	if x != nil {
		return x.AtUnix
	}
	return 0
}

type CoreFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*CoreFrame_ConfigPush
	//	*CoreFrame_UserOp
	//	*CoreFrame_Command
	//	*CoreFrame_OnlinePolicy
	Frame         isCoreFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreFrame) Reset() {
	*x = CoreFrame{}
	mi := &file_chiral_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreFrame) ProtoMessage() {}

func (x *CoreFrame) ProtoReflect() protoreflect.Message {
	mi := &file_chiral_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreFrame.ProtoReflect.Descriptor instead.
func (*CoreFrame) Descriptor() ([]byte, []int) {
	return file_chiral_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *CoreFrame) GetFrame() isCoreFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *CoreFrame) GetConfigPush() *ConfigPush {
	if x != nil {
		if x, ok := x.Frame.(*CoreFrame_ConfigPush); ok {
			return x.ConfigPush
		}
	}
	return nil
}

func (x *CoreFrame) GetUserOp() *UserOp {
	if x != nil {
		if x, ok := x.Frame.(*CoreFrame_UserOp); ok {
			return x.UserOp
		}
	}
	return nil
}

func (x *CoreFrame) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Frame.(*CoreFrame_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *CoreFrame) GetOnlinePolicy() *OnlinePolicy {
	if x != nil {
		if x, ok := x.Frame.(*CoreFrame_OnlinePolicy); ok {
			return x.OnlinePolicy
		}
	}
	return nil
}

type isCoreFrame_Frame interface {
	isCoreFrame_Frame()
}

type CoreFrame_ConfigPush struct {
	ConfigPush *ConfigPush `protobuf:"bytes,1,opt,name=config_push,json=configPush,proto3,oneof"`
}

type CoreFrame_UserOp struct {
	UserOp *UserOp `protobuf:"bytes,2,opt,name=user_op,json=userOp,proto3,oneof"`
}

type CoreFrame_Command struct {
	Command *Command `protobuf:"bytes,3,opt,name=command,proto3,oneof"`
}

type CoreFrame_OnlinePolicy struct {
	OnlinePolicy *OnlinePolicy `protobuf:"bytes,4,opt,name=online_policy,json=onlinePolicy,proto3,oneof"`
}

func (*CoreFrame_ConfigPush) isCoreFrame_Frame() {}

func (*CoreFrame_UserOp) isCoreFrame_Frame() {}

func (*CoreFrame_Command) isCoreFrame_Frame() {}

func (*CoreFrame_OnlinePolicy) isCoreFrame_Frame() {}

// OnlinePolicy switches the agent's online-address polling on or off.
//
// Off by default and off unless Core says otherwise: polling costs one
// `xray api` subprocess per round plus one per online user, and an operator
// who has not asked for the feature should not pay for it.
//
// Deliberately carries no list of users to watch. Core knows which credentials
// are limited, but sending that list would hand every rented VPS the display
// names, user ids and profile ids of subscribers it does not serve — the
// isolation that per-node credentials buy in the first place. The agent only
// ever sees its own online users; the filtering happens at Core, for free.
type OnlinePolicy struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Enabled bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Seconds between rounds. The interval IS the sampling error: a session that
	// opens and closes between two rounds is invisible, and Xray drops an address
	// from the set within about two seconds of disconnection — there is no
	// lingering window to catch it in.
	IntervalSeconds int32 `protobuf:"varint,2,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OnlinePolicy) Reset() {
	*x = OnlinePolicy{}
	mi := &file_chiral_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlinePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlinePolicy) ProtoMessage() {}

func (x *OnlinePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_chiral_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlinePolicy.ProtoReflect.Descriptor instead.
func (*OnlinePolicy) Descriptor() ([]byte, []int) {
	return file_chiral_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *OnlinePolicy) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *OnlinePolicy) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

// ConfigPush delivers a complete config.json. Core has already validated it
// with `xray -test` before pushing. Rollback is expressed as a ConfigPush of
// an older version's content (with a new version number); the agent keeps no
// local history.
type ConfigPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ConfigJson    []byte                 `protobuf:"bytes,2,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPush) Reset() {
	*x = ConfigPush{}
	mi := &file_chiral_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPush) ProtoMessage() {}

func (x *ConfigPush) ProtoReflect() protoreflect.Message {
	mi := &file_chiral_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPush.ProtoReflect.Descriptor instead.
func (*ConfigPush) Descriptor() ([]byte, []int) {
	return file_chiral_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigPush) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigPush) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

// UserOp adds/removes a client on a live inbound via Xray-core's
// HandlerService, without restarting the core.
// Implemented in M3; account payload shape is finalized then.
type UserOp struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Kind       UserOpKind             `protobuf:"varint,1,opt,name=kind,proto3,enum=chiral.v1.UserOpKind" json:"kind,omitempty"`
	InboundTag string                 `protobuf:"bytes,2,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	// Per-credential stats key, e.g. "alice@tokyo-reality".
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// JSON-encoded account object (uuid/password/flow...), draft until M3.
	AccountJson   []byte `protobuf:"bytes,4,opt,name=account_json,json=accountJson,proto3" json:"account_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOp) Reset() {
	*x = UserOp{}
	mi := &file_chiral_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOp) ProtoMessage() {}

func (x *UserOp) ProtoReflect() protoreflect.Message {
	mi := &file_chiral_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOp.ProtoReflect.Descriptor instead.
func (*UserOp) Descriptor() ([]byte, []int) {
	return file_chiral_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *UserOp) GetKind() UserOpKind {
	if x != nil {
		return x.Kind
	}
	return UserOpKind_USER_OP_KIND_UNSPECIFIED
}

func (x *UserOp) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

func (x *UserOp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserOp) GetAccountJson() []byte {
	if x != nil {
		return x.AccountJson
	}
	return nil
}

// Command is a small imperative from Core.
type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Cmd:
	//
	//	*Command_RestartXray
	//	*Command_ReportNow
	Cmd           isCommand_Cmd `protobuf_oneof:"cmd"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_chiral_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_chiral_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_chiral_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *Command) GetCmd() isCommand_Cmd {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *Command) GetRestartXray() *RestartXray {
	if x != nil {
		if x, ok := x.Cmd.(*Command_RestartXray); ok {
			return x.RestartXray
		}
	}
	return nil
}

func (x *Command) GetReportNow() *ReportNow {
	if x != nil {
		if x, ok := x.Cmd.(*Command_ReportNow); ok {
			return x.ReportNow
		}
	}
	return nil
}

type isCommand_Cmd interface {
	isCommand_Cmd()
}

type Command_RestartXray struct {
	RestartXray *RestartXray `protobuf:"bytes,1,opt,name=restart_xray,json=restartXray,proto3,oneof"`
}

type Command_ReportNow struct {
	ReportNow *ReportNow `protobuf:"bytes,2,opt,name=report_now,json=reportNow,proto3,oneof"`
}

func (*Command_RestartXray) isCommand_Cmd() {}

func (*Command_ReportNow) isCommand_Cmd() {}

// RestartXray asks the agent to restart the Xray-core process.
type RestartXray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartXray) Reset() {
	*x = RestartXray{}
	mi := &file_chiral_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartXray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartXray) ProtoMessage() {}

func (x *RestartXray) ProtoReflect() protoreflect.Message {
	mi := &file_chiral_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartXray.ProtoReflect.Descriptor instead.
func (*RestartXray) Descriptor() ([]byte, []int) {
	return file_chiral_v1_agent_proto_rawDescGZIP(), []int{17}
}

// ReportNow asks the agent to send a Heartbeat (and StatsReport once
// implemented) immediately.
type ReportNow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportNow) Reset() {
	*x = ReportNow{}
	mi := &file_chiral_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportNow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportNow) ProtoMessage() {}

func (x *ReportNow) ProtoReflect() protoreflect.Message {
	mi := &file_chiral_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportNow.ProtoReflect.Descriptor instead.
func (*ReportNow) Descriptor() ([]byte, []int) {
	return file_chiral_v1_agent_proto_rawDescGZIP(), []int{18}
}

var File_chiral_v1_agent_proto protoreflect.FileDescriptor

const file_chiral_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x15chiral/v1/agent.proto\x12\tchiral.v1\"q\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"join_token\x18\x01 \x01(\tR\tjoinToken\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\"K\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1e\n" +
	"\n" +
	"credential\x18\x02 \x01(\tR\n" +
	"credential\"\xb9\x02\n" +
	"\n" +
	"AgentFrame\x12(\n" +
	"\x05hello\x18\x01 \x01(\v2\x10.chiral.v1.HelloH\x00R\x05hello\x124\n" +
	"\theartbeat\x18\x02 \x01(\v2\x14.chiral.v1.HeartbeatH\x00R\theartbeat\x12.\n" +
	"\x05stats\x18\x03 \x01(\v2\x16.chiral.v1.StatsReportH\x00R\x05stats\x125\n" +
	"\n" +
	"config_ack\x18\x04 \x01(\v2\x14.chiral.v1.ConfigAckH\x00R\tconfigAck\x12(\n" +
	"\x05event\x18\x05 \x01(\v2\x10.chiral.v1.EventH\x00R\x05event\x121\n" +
	"\x06online\x18\x06 \x01(\v2\x17.chiral.v1.OnlineReportH\x00R\x06onlineB\a\n" +
	"\x05frame\"\x85\x01\n" +
	"\x05Hello\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12!\n" +
	"\fxray_version\x18\x03 \x01(\tR\vxrayVersion\x12\x1b\n" +
	"\tpublic_ip\x18\x04 \x01(\tR\bpublicIp\"\xbd\x03\n" +
	"\tHeartbeat\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12$\n" +
	"\x0emem_used_bytes\x18\x02 \x01(\x04R\fmemUsedBytes\x12&\n" +
	"\x0fmem_total_bytes\x18\x03 \x01(\x04R\rmemTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\x04 \x01(\x04R\rdiskUsedBytes\x12(\n" +
	"\x10disk_total_bytes\x18\x05 \x01(\x04R\x0ediskTotalBytes\x12\x1c\n" +
	"\n" +
	"net_tx_bps\x18\x06 \x01(\x04R\bnetTxBps\x12\x1c\n" +
	"\n" +
	"net_rx_bps\x18\a \x01(\x04R\bnetRxBps\x123\n" +
	"\n" +
	"xray_state\x18\b \x01(\x0e2\x14.chiral.v1.XrayStateR\txrayState\x12%\n" +
	"\x0econfig_version\x18\t \x01(\x03R\rconfigVersion\x12!\n" +
	"\fxray_version\x18\n" +
	" \x01(\tR\vxrayVersion\x124\n" +
	"\x16installed_xray_version\x18\v \x01(\tR\x14installedXrayVersion\"=\n" +
	"\vStatsReport\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.chiral.v1.StatEntryR\aentries\"\x95\x01\n" +
	"\tStatEntry\x12*\n" +
	"\x05scope\x18\x01 \x01(\x0e2\x14.chiral.v1.StatScopeR\x05scope\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fuplink_bytes\x18\x03 \x01(\x04R\vuplinkBytes\x12%\n" +
	"\x0edownlink_bytes\x18\x04 \x01(\x04R\rdownlinkBytes\"U\n" +
	"\tConfigAck\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x18\n" +
	"\aapplied\x18\x02 \x01(\bR\aapplied\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"p\n" +
	"\fOnlineReport\x12\x17\n" +
	"\aat_unix\x18\x01 \x01(\x03R\x06atUnix\x12\x1a\n" +
	"\bcomplete\x18\x02 \x01(\bR\bcomplete\x12+\n" +
	"\x05users\x18\x03 \x03(\v2\x15.chiral.v1.OnlineUserR\x05users\"I\n" +
	"\n" +
	"OnlineUser\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12%\n" +
	"\x03ips\x18\x02 \x03(\v2\x13.chiral.v1.OnlineIPR\x03ips\"@\n" +
	"\bOnlineIP\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12$\n" +
	"\x0elast_seen_unix\x18\x02 \x01(\x03R\flastSeenUnix\"d\n" +
	"\x05Event\x12(\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x14.chiral.v1.EventKindR\x04kind\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\aat_unix\x18\x03 \x01(\x03R\x06atUnix\"\xec\x01\n" +
	"\tCoreFrame\x128\n" +
	"\vconfig_push\x18\x01 \x01(\v2\x15.chiral.v1.ConfigPushH\x00R\n" +
	"configPush\x12,\n" +
	"\auser_op\x18\x02 \x01(\v2\x11.chiral.v1.UserOpH\x00R\x06userOp\x12.\n" +
	"\acommand\x18\x03 \x01(\v2\x12.chiral.v1.CommandH\x00R\acommand\x12>\n" +
	"\ronline_policy\x18\x04 \x01(\v2\x17.chiral.v1.OnlinePolicyH\x00R\fonlinePolicyB\a\n" +
	"\x05frame\"S\n" +
	"\fOnlinePolicy\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12)\n" +
	"\x10interval_seconds\x18\x02 \x01(\x05R\x0fintervalSeconds\"G\n" +
	"\n" +
	"ConfigPush\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x1f\n" +
	"\vconfig_json\x18\x02 \x01(\fR\n" +
	"configJson\"\x8d\x01\n" +
	"\x06UserOp\x12)\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x15.chiral.v1.UserOpKindR\x04kind\x12\x1f\n" +
	"\vinbound_tag\x18\x02 \x01(\tR\n" +
	"inboundTag\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12!\n" +
	"\faccount_json\x18\x04 \x01(\fR\vaccountJson\"\x84\x01\n" +
	"\aCommand\x12;\n" +
	"\frestart_xray\x18\x01 \x01(\v2\x16.chiral.v1.RestartXrayH\x00R\vrestartXray\x125\n" +
	"\n" +
	"report_now\x18\x02 \x01(\v2\x14.chiral.v1.ReportNowH\x00R\treportNowB\x05\n" +
	"\x03cmd\"\r\n" +
	"\vRestartXray\"\v\n" +
	"\tReportNow*m\n" +
	"\tXrayState\x12\x1a\n" +
	"\x16XRAY_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12XRAY_STATE_RUNNING\x10\x01\x12\x16\n" +
	"\x12XRAY_STATE_STOPPED\x10\x02\x12\x14\n" +
	"\x10XRAY_STATE_ERROR\x10\x03*m\n" +
	"\tStatScope\x12\x1a\n" +
	"\x16STAT_SCOPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12STAT_SCOPE_INBOUND\x10\x01\x12\x17\n" +
	"\x13STAT_SCOPE_OUTBOUND\x10\x02\x12\x13\n" +
	"\x0fSTAT_SCOPE_USER\x10\x03*y\n" +
	"\tEventKind\x12\x1a\n" +
	"\x16EVENT_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EVENT_KIND_XRAY_CRASHED\x10\x01\x12\x1d\n" +
	"\x19EVENT_KIND_XRAY_RESTARTED\x10\x02\x12\x14\n" +
	"\x10EVENT_KIND_ERROR\x10\x03*Y\n" +
	"\n" +
	"UserOpKind\x12\x1c\n" +
	"\x18USER_OP_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10USER_OP_KIND_ADD\x10\x01\x12\x17\n" +
	"\x13USER_OP_KIND_REMOVE\x10\x022\x8f\x01\n" +
	"\fAgentService\x12C\n" +
	"\bRegister\x12\x1a.chiral.v1.RegisterRequest\x1a\x1b.chiral.v1.RegisterResponse\x12:\n" +
	"\aChannel\x12\x15.chiral.v1.AgentFrame\x1a\x14.chiral.v1.CoreFrame(\x010\x01B6Z4github.com/SayukiOvO/chiral/proto/chiral/v1;chiralv1b\x06proto3"

var (
	file_chiral_v1_agent_proto_rawDescOnce sync.Once
	file_chiral_v1_agent_proto_rawDescData []byte
)

func file_chiral_v1_agent_proto_rawDescGZIP() []byte {
	file_chiral_v1_agent_proto_rawDescOnce.Do(func() {
		file_chiral_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chiral_v1_agent_proto_rawDesc), len(file_chiral_v1_agent_proto_rawDesc)))
	})
	return file_chiral_v1_agent_proto_rawDescData
}

var file_chiral_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_chiral_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_chiral_v1_agent_proto_goTypes = []any{
	(XrayState)(0),           // 0: chiral.v1.XrayState
	(StatScope)(0),           // 1: chiral.v1.StatScope
	(EventKind)(0),           // 2: chiral.v1.EventKind
	(UserOpKind)(0),          // 3: chiral.v1.UserOpKind
	(*RegisterRequest)(nil),  // 4: chiral.v1.RegisterRequest
	(*RegisterResponse)(nil), // 5: chiral.v1.RegisterResponse
	(*AgentFrame)(nil),       // 6: chiral.v1.AgentFrame
	(*Hello)(nil),            // 7: chiral.v1.Hello
	(*Heartbeat)(nil),        // 8: chiral.v1.Heartbeat
	(*StatsReport)(nil),      // 9: chiral.v1.StatsReport
	(*StatEntry)(nil),        // 10: chiral.v1.StatEntry
	(*ConfigAck)(nil),        // 11: chiral.v1.ConfigAck
	(*OnlineReport)(nil),     // 12: chiral.v1.OnlineReport
	(*OnlineUser)(nil),       // 13: chiral.v1.OnlineUser
	(*OnlineIP)(nil),         // 14: chiral.v1.OnlineIP
	(*Event)(nil),            // 15: chiral.v1.Event
	(*CoreFrame)(nil),        // 16: chiral.v1.CoreFrame
	(*OnlinePolicy)(nil),     // 17: chiral.v1.OnlinePolicy
	(*ConfigPush)(nil),       // 18: chiral.v1.ConfigPush
	(*UserOp)(nil),           // 19: chiral.v1.UserOp
	(*Command)(nil),          // 20: chiral.v1.Command
	(*RestartXray)(nil),      // 21: chiral.v1.RestartXray
	(*ReportNow)(nil),        // 22: chiral.v1.ReportNow
}
var file_chiral_v1_agent_proto_depIdxs = []int32{
	7,  // 0: chiral.v1.AgentFrame.hello:type_name -> chiral.v1.Hello
	8,  // 1: chiral.v1.AgentFrame.heartbeat:type_name -> chiral.v1.Heartbeat
	9,  // 2: chiral.v1.AgentFrame.stats:type_name -> chiral.v1.StatsReport
	11, // 3: chiral.v1.AgentFrame.config_ack:type_name -> chiral.v1.ConfigAck
	15, // 4: chiral.v1.AgentFrame.event:type_name -> chiral.v1.Event
	12, // 5: chiral.v1.AgentFrame.online:type_name -> chiral.v1.OnlineReport
	0,  // 6: chiral.v1.Heartbeat.xray_state:type_name -> chiral.v1.XrayState
	10, // 7: chiral.v1.StatsReport.entries:type_name -> chiral.v1.StatEntry
	1,  // 8: chiral.v1.StatEntry.scope:type_name -> chiral.v1.StatScope
	13, // 9: chiral.v1.OnlineReport.users:type_name -> chiral.v1.OnlineUser
	14, // 10: chiral.v1.OnlineUser.ips:type_name -> chiral.v1.OnlineIP
	2,  // 11: chiral.v1.Event.kind:type_name -> chiral.v1.EventKind
	18, // 12: chiral.v1.CoreFrame.config_push:type_name -> chiral.v1.ConfigPush
	19, // 13: chiral.v1.CoreFrame.user_op:type_name -> chiral.v1.UserOp
	20, // 14: chiral.v1.CoreFrame.command:type_name -> chiral.v1.Command
	17, // 15: chiral.v1.CoreFrame.online_policy:type_name -> chiral.v1.OnlinePolicy
	3,  // 16: chiral.v1.UserOp.kind:type_name -> chiral.v1.UserOpKind
	21, // 17: chiral.v1.Command.restart_xray:type_name -> chiral.v1.RestartXray
	22, // 18: chiral.v1.Command.report_now:type_name -> chiral.v1.ReportNow
	4,  // 19: chiral.v1.AgentService.Register:input_type -> chiral.v1.RegisterRequest
	6,  // 20: chiral.v1.AgentService.Channel:input_type -> chiral.v1.AgentFrame
	5,  // 21: chiral.v1.AgentService.Register:output_type -> chiral.v1.RegisterResponse
	16, // 22: chiral.v1.AgentService.Channel:output_type -> chiral.v1.CoreFrame
	21, // [21:23] is the sub-list for method output_type
	19, // [19:21] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_chiral_v1_agent_proto_init() }
func file_chiral_v1_agent_proto_init() {
	if File_chiral_v1_agent_proto != nil {
		return
	}
	file_chiral_v1_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentFrame_Hello)(nil),
		(*AgentFrame_Heartbeat)(nil),
		(*AgentFrame_Stats)(nil),
		(*AgentFrame_ConfigAck)(nil),
		(*AgentFrame_Event)(nil),
		(*AgentFrame_Online)(nil),
	}
	file_chiral_v1_agent_proto_msgTypes[12].OneofWrappers = []any{
		(*CoreFrame_ConfigPush)(nil),
		(*CoreFrame_UserOp)(nil),
		(*CoreFrame_Command)(nil),
		(*CoreFrame_OnlinePolicy)(nil),
	}
	file_chiral_v1_agent_proto_msgTypes[16].OneofWrappers = []any{
		(*Command_RestartXray)(nil),
		(*Command_ReportNow)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chiral_v1_agent_proto_rawDesc), len(file_chiral_v1_agent_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chiral_v1_agent_proto_goTypes,
		DependencyIndexes: file_chiral_v1_agent_proto_depIdxs,
		EnumInfos:         file_chiral_v1_agent_proto_enumTypes,
		MessageInfos:      file_chiral_v1_agent_proto_msgTypes,
	}.Build()
	File_chiral_v1_agent_proto = out.File
	file_chiral_v1_agent_proto_goTypes = nil
	file_chiral_v1_agent_proto_depIdxs = nil
}
